# Generated by Django 2.0.6 on 2018-06-04 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('languages', models.CharField(max_length=100)),
                ('climate', models.CharField(max_length=100)),
                ('items_needed', models.CharField(max_length=2000)),
            ],
        ),
    ]
